#!/usr/bin/env bash
# Load Balancer Config

sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

printf %s 'backend web-backend
        balance roundrobin
        server 5686-web-01 3.94.193.31 check
        server 5686-web-02 54.221.181.203 check

frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
