#!/usr/bin/env bash
# Install nginx

sudo apt update
sudo apt install nginx -y

sudo touch /var/www/html/index.html
echo "Holberton School" >> /var/www/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
