#!/usr/bin/env bash
# Install nginx

sudo apt update
sudo apt install nginx -y

mkdir /var/www/html

touch /var/www/html/index.html


echo "Holberton School" > /var/www/html/index.html


printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
