#!/usr/bin/env bash
# Install nginx

sudo apt update
sudo apt install nginx -y

echo "Holberton School" | sudo tee /var/www/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
