#!/usr/bin/env bash
# comment
sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" >> /var/www/html/index.html

echo "server {" > /etc/nginx/sites-available/default
echo "	

sudo service nginx restart
