#!/usr/bin/env bash
# Redirection

sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html

printf %s "server {
	listen 80 default_server;
        listen [::]:80 default_server;

	root /var/www/html;

	index index.html;
	
	server_name _;
        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=M-ThkvdcYmo/;
        }
	
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
