#!/usr/bin/env bash
# comment
sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" >> /var/www/html/index.html

echo 'server {' > /etc/nginx/sites-available/default
echo '        listen 80 default_server;' >> /etc/nginx/sites-available/default
echo '        listen [::]:80 default_server;' >> /etc/nginx/sites-available/default
echo '        root /var/www/html;' >> /etc/nginx/sites-available/default

echo '        index index.html;' >> /etc/nginx/sites-available/default

echo '        server_name _;' >> /etc/nginx/sites-available/default

echo '        location /redirect_me {' >> /etc/nginx/sites-available/default
echo '           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;' >> /etc/nginx/sites-available/default
echo '        }' >> /etc/nginx/sites-available/default
echo '}' >> /etc/nginx/sites-available/default

sudo service nginx restart
